### PR TITLE
Fix Wolfhunter dungeon achievements

### PR DESCRIPTION
**Pull request by Shredder121**
Lists taken from the UESP project, and sorted according to the
achievement index, which the achievement journal seems to sort by when
the achievement hasn't been unlocked (and seems to be largely compatible with the current sort order).

Lists available at [Wolfhunter::General][] and [Wolfhunter::Veteran][].

[wolfhunter::general]: http://esolog.uesp.net/viewlog.php?record=achievements&filter=categoryName&filterid=Wolfhunter%3A%3AGeneral&sort=achievementindex
[wolfhunter::veteran]: http://esolog.uesp.net/viewlog.php?record=achievements&filter=categoryName&filterid=Wolfhunter%3A%3AVeteran&sort=achievementindex

### CODE REVIEW

**Comment by Shredder121** [comment]
Just want to say I'm really happy with what you do, it makes winding down just so much easier.

**Comment by Shredder121** [comment]
(I held shift while pressing enter, apparently that's Close and comment)

**Comment by Shredder121** [comment]
Note: `achievementindex` is dependent on the logger from uesp at the point of logging not having gotten any of the achievements (which maybe is a decent tradeoff, since at least the UESP logs are open).
I haven't found a way of finding out what the original ordering is (so anyone checking the achievement list has a deterministic way of finding out a particular achievement being in the list or not).

That said, it is IMO still the best ordering key at the moment.
Or do you think we should just order by achievement ID, since that doesn't require us looking up another source (be it your running ESO, or UESP)? *That does mean that some `General` and `Veteran` achievements will be interleaved, so maybe not a good idea.

**Comment by Shredder121** [comment]
@iFedix just a ping, don't know if you have notifications on?

**Comment by iFedix** [comment]
Hey! Yeah notifications was off! I fixed some achievements you indicated to me in the new updated version I'm currently working on. Thank you! Anyway I can't merge your files because for example the challenger achievements are not supposed as "composed". For composed (and ok, I don't know if the term is exact but did not want to find another one, too lazy lol) I indicated achievements that needs other achievements from multiple dungeons like [this for example](https://en.uesp.net/wiki/Online:Vanquisher_of_the_Covenant). 
Also, to indicate achievement ids I manually dumped all the ids in the game and fill the correspondant tables manually.. I did not think about an order or so on, because my idea is that this is only a partial version of the achievement tracker. I'd like to do something like [this addon does](https://www.esoui.com/downloads/info2028-WykkydAchievementTracker-SummersetAPI.html#info) instead of logging everything in the main chat. But to do this I need to learn how to build windows and ui stuff and so how to integrate xml and lua and so on which I'm currently tryng to do in my free time (and I don't have a lot). So yeah, for now I have just followed random ordering I guess lol I spent a lot of time looking for the ids and filling the tables...

**Comment by Shredder121** [comment]
> I indicated achievements that needs other achievements from multiple dungeons

Ah I see, I thought they were just meant to be composed of multiple, which the Challenger was.



> which I'm currently tryng to do in my free time (and I don't have a lot).

I feel you, that's fine though. If you put up issues that can be worked on, and I have some free time while winding down, I can give some things a whirl myself.
Although I'm sure you'd want to do the main UI code?

But if you're for example not sure whether some achievement lists are correct I can check them?

**Comment by iFedix** [comment]
I'm learning how to integrate xml for ui and lua! Anyway yes, it would be amazing if you could check the achievement lists! As I wrote in the esoui changelog, I hardcoded everything there so maybe I could have missed something or made some errors (which you have already found in wolfhunter dungeons lol). Thank you!

**Comment by Shredder121** [comment]
Yeah, I did start on the Horns of the Reach, but first wanted to wait out whether this was something you'd accept. I'll at least now with the knowledge on the Composed achievements continue.
Maybe it should be `Single` and `Multiple`? If it's only used for cross-dungeon achievements?
Anyway, thanks for your time.

**Comment by iFedix** [comment]
Yeah, that's the idea! Multiple could be a better name, because it's inteded as cross dungeon achievs. Anyway sure, I'll accept your fixes! Also even if I won't accept your merge requests (I have some code which is in progress and test and so I'm not pushing it on git for now) I would manually add your fixes in the version I'm currently working on. Thank you!

**Comment by iFedix** [comment]
PS: [This is the file where I had a look for the achievs](https://mega.nz/#!T5AFSSrS!0moEZIJs6ZzQfLGWXU3tWoVlUq_YTGbkD2p_gLHbbgE). It's a complete dump using eso api!

**Pull request closed without merging**
